<?php

namespace le\Boncoin\MyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CylindrieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CylindrieRepository extends EntityRepository
{
}
