<?php

namespace le\Boncoin\MyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotoRepository extends EntityRepository
{
}
